### ISSUE TITLE
Use Cargo features for CLI deps. 

### ISSUE THREAD

**Issue by thedodd** [apyrgio/tindercrypt#1]
Hello! Awesome work on this project! Stoked to start using it. 

With the way the dependencies are currently structured, the CLI deps will still be pulled in and compiled by even when this crate is only being used in library form. 

To mitigate this, and to preserve current install behavior, I would recommend adding a default `cli` feature. Then set the 3 CLI specific deps to `optional=true` and declare them as being part of the `cli` feature.

That should help to cut down on the number of deps for folks using this as a library. To be sure, folks will have to set their dependency on this lib to `--no-default-features` To reap those benefits.

**Comment by thedodd** [comment]
I’m happy to open a PR for this in a few hours. AFK right now.

**Comment by apyrgio** [comment]
Right, I was waiting for an official solution to rust-lang/cargo#1982, but unfortunately there's none yet. Anyway, your approach is reasonable, so let's go with it. If you have the time to send a PR, that would be great. Else, I can write something myself.

P.S. Thanks for the kind words :-)
