### ISSUE TITLE
impl std Error for tindercrypt Error

### ISSUE THREAD

**Issue by thedodd** [apyrgio/tindercrypt#3]
Hello again! Meant to pop this issue earlier. I think it would be nice to implement `std::error::Error` for the [tindercrypt::error::Error](https://docs.rs/tindercrypt/0.2.1/tindercrypt/errors/enum.Error.html) type. 

Happy to open a PR for this soon, but I wanted to open this issue just in case someone else beats me to it `:)`.

**Comment by apyrgio** [comment]
You're right, implementing `Error` would help a lot of people. I've actually done something similar in another crate of mine using `thiserror`, which has various other goodies. I'll open a PR here to do the same.
