### ISSUE TITLE
Is it safe to re-use RingCryptor?

### ISSUE THREAD

**Issue by thedodd** [apyrgio/tindercrypt#5]
Just wondering if it is safe to re-use a `RingCryptor` instance? Or is it expected that a new instance be created before every encryption/decryption routine?

**Comment by thedodd** [comment]
Eh, looking at the code. The cryptor is dead simple, so there shouldn't be any overhead in creating a new one.

**Comment by apyrgio** [comment]
Just confirming that, yes, in the common case it's safe to reuse, since it doesn't have any state. Note however that if you specify any additional data (see `.with_aad()`), then you should overwrite them or create a new `RingCryptor` instance.
